### ISSUE TITLE
Build Failure with GINKGO_CHECK_CIRCULAR_DEPS enabled

### ISSUE THREAD

**Issue by MarcelKoch** [ginkgo-project/ginkgo#782] opened 2021-06-04 11:45 UTC
Building the default target with `GINKGO_CHECK_CIRCULAR_DEPS=ON` results in a compilation error. More specifically, the target `ginkgo_cuda_headers` fails with the error message:

```
ginkgo/cuda/base/math.hpp:40:10: fatal error: thrust/complex.h: No such file or directory
   40 | #include <thrust/complex.h>
      |          ^~~~~~~~~~~~~~~~~~
```

My guess is that this is caused by missing includes from cuda. Checking the verbose make output shows that the default C++ compiler is used and no include path for cuda are given.

**Comment by pratikvn** [comment] 2021-06-04 11:51
Can you make sure that your `INCLUDE_PATH`, `CPATH` include the cuda (thrust) include paths ?  We have had this issue before, I think. Sometimes the cuda auxiliary libraries change paths with cuda installations.

**Comment by upsj** [comment] 2021-06-04 11:53
Oh and what CUDA version are you using? nvcc should add CUDA-specific include paths automatically, but AFAIK thrust has only become part of CUDA recently

**Comment by MarcelKoch** [comment] 2021-06-04 12:01
@upsj @pratikvn I'm using cuda V11.3.109. Neither `INCLUDE_PATH` nor `CPATH` include the cuda path on my system, after setting up cuda. Additionally, adjusting these paths is not mentioned in the cuda installation guide at all, so I would suggest that this should be fixed on the gingko side.

A possible solution is to add the include path in the cmake function`ginkgo_check_headers` similar to the HIP handling.

**Comment by tcojean** [comment] 2021-06-04 12:35
It's not a library's job to detect the environment settings of the user.

**Comment by upsj** [comment] 2021-06-04 12:37
I can reproduce this on my system, it looks like the headers are being compiled with `c++` instead of `nvcc`.

**Comment by tcojean** [comment] 2021-06-04 12:38
If it's only a wrong compiler usage, then I guess that can be fixed in a simpler fashion.

**Comment by upsj** [comment] 2021-06-04 12:40
Yes, we have some header files that include CUDA-specific headers, but are named `.hpp`. So either we explicitly compile everything as `CUDA` or we rename those headers to `.cuh`

**Closed** 2021-06-07 12:49 UTC
Labels: is:bug, is:confirmed, reg:build
