### ISSUE TITLE
NaN Residuals with CUDA GMRES+ParILUT -matrix part 3 again 

### ISSUE THREAD

**Issue by iontcheva** [ginkgo-project/ginkgo#1489] opened 2023-12-05 22:18 UTC
[cis.mtx.gz.part-ac.gz](https://github.com/ginkgo-project/ginkgo/files/13573530/cis.mtx.gz.part-ac.gz)

**Comment by upsj** [comment] 2023-12-06 02:20
Duplicate of #1486

**Closed by upsj** 2023-12-06 02:20 UTC
