### ISSUE TITLE
Installation issue (Help please)

### ISSUE THREAD

**Issue by sparse-bit** [ginkgo-project/ginkgo#1126] opened 2022-09-27 08:53 UTC
..........
[  1%] Building CUDA object cuda/CMakeFiles/ginkgo_cuda.dir/base/device_matrix_data_kernels.cu.o
/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"
          detected during instantiation of type "std::make_integer_sequence<std::size_t, _Num>"
(340): here

/home/hh/SolverSelection/ginkgo-develop/include/ginkgo/core/base/machine_topology.hpp(418): warning: attribute does not apply to any entity

3 errors detected in the compilation of "/tmp/tmpxft_000313ad_00000000-6_device_matrix_data_kernels.cpp1.ii".
make[2]: *** [cuda/CMakeFiles/ginkgo_cuda.dir/build.make:63: cuda/CMakeFiles/ginkgo_cuda.dir/base/device_matrix_data_kernels.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4196: cuda/CMakeFiles/ginkgo_cuda.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
.........

**Comment by upsj** [comment] 2022-09-27 08:59
Thanks for your report! Could you please provide some more context to the build issues? What (CUDA and C++) compilers are you using at which version? What is the full output of the CMake configuration step?

From a first glance, it looks like you might be using an incompatible combination of CUDA compiler/libraries and C++ compiler. You can check our [README.md](https://github.com/ginkgo-project/ginkgo/blob/develop/README.md) for the exact requirements.

**Comment by sparse-bit** [comment] 2022-09-27 09:04
Thanks for your reply. 
I am using : g++ (Ubuntu 7.5.0-6ubuntu2) 7.5.0  and CUDA Version: 11.4 .

CMake output : 
-----------------------------------------------------------------------------------------------------
(base) xxxxxxxxx/SolverSelection/ginkgo-develop$ cmake  -G "Unix Makefiles"
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- GINKGO_BUILD_TESTS is ON, enabling GINKGO_BUILD_REFERENCE
-- Could NOT find PAPI (missing: PAPI_LIBRARY PAPI_INCLUDE_DIR)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.10.0")
-- Looking for HWLOC - found version 2.1.0
-- Looking for hwloc_topology_init
-- Looking for hwloc_topology_init - found
-- Fetching external GTest
fatal: not a git repository (or any of the parent directories): .git
-- Ginkgo is not in a git repository, so no git hook was installed
-- Fetching external GFlags
-- Fetching external RapidJSON
-- No OpenCV found, disabling examples with video output
--
---------------------------------------------------------------------------------------------------------
--
--    Summary of Configuration for Ginkgo (version 1.5.0 with tag develop)
--
--    Ginkgo configuration:
--        CMAKE_BUILD_TYPE:                           Release
--        BUILD_SHARED_LIBS:                          ON
--        CMAKE_INSTALL_PREFIX:                       /usr/local
--        PROJECT_SOURCE_DIR:                         /home/hh/hh/ginkgo-develop
--        PROJECT_BINARY_DIR:                         /home/hh/hh/ginkgo-develop
--        CMAKE_CXX_COMPILER:                         GNU 7.5.0 on platform Linux x86_64
--                                                    /usr/bin/c++
--    User configuration:
--      Enabled modules:
--        GINKGO_BUILD_OMP:                           ON
--        GINKGO_BUILD_MPI:                           ON
--        GINKGO_BUILD_REFERENCE:                     ON
--        GINKGO_BUILD_CUDA:                          ON
--        GINKGO_BUILD_HIP:                           OFF
--        GINKGO_BUILD_DPCPP:                         OFF
--      Enabled features:
--        GINKGO_MIXED_PRECISION:                     OFF
--      Tests, benchmarks and examples:
--        GINKGO_BUILD_TESTS:                         ON
--        GINKGO_FAST_TESTS:                          OFF
--        GINKGO_BUILD_EXAMPLES:                      ON
--        GINKGO_EXTLIB_EXAMPLE:
--        GINKGO_BUILD_BENCHMARKS:                    ON
--        GINKGO_BENCHMARK_ENABLE_TUNING:             OFF
--      Documentation:
--        GINKGO_BUILD_DOC:                           OFF
--        GINKGO_VERBOSE_LEVEL:                       1
--
---------------------------------------------------------------------------------------------------------
--
--      Developer Tools:
--        GINKGO_DEVEL_TOOLS:                         OFF
--        GINKGO_WITH_CLANG_TIDY:                     OFF
--        GINKGO_WITH_IWYU:                           OFF
--        GINKGO_CHECK_CIRCULAR_DEPS:                 OFF
--        GINKGO_WITH_CCACHE:                         ON
---------------------------------------------------------------------------------------------------------
--
--      Components:
--        GINKGO_BUILD_HWLOC:                         ON
--
--  Detailed information (More compiler flags, module configuration) can be found in detailed.log
--
--
--  Now, run  cmake --build .  to compile Ginkgo!

**Comment by upsj** [comment] 2022-09-27 15:09
I am unable to reproduce the issue. Can you provide more details on your system setup, e.g. distribution, and double-check that CMake picked up the CUDA 11.4 compiler? You can check for the CMAKE_CUDA_COMPILER variable in CMakeCache.txt

**Comment by upsj** [comment] 2022-11-02 09:45
Can you give us an update on this issue? Otherwise, we will have to close it soon.

**Closed** 2022-11-21 21:38 UTC
