### ISSUE TITLE
NaN Residuals with CUDA GMRES+ParILUT - the rhs 

### ISSUE THREAD

**Issue by iontcheva** [ginkgo-project/ginkgo#1494] opened 2023-12-05 22:21 UTC
[cis_rhs.mtx.gz](https://github.com/ginkgo-project/ginkgo/files/13573549/cis_rhs.mtx.gz)

**Comment by upsj** [comment] 2023-12-06 02:21
Duplicate of #1486

**Closed by upsj** 2023-12-06 02:21 UTC
