### ISSUE TITLE
[Error] inverse-iteration

### ISSUE THREAD

**Issue by nghiakvnvsd** [ginkgo-project/ginkgo#606] opened 2020-07-30 14:56 UTC
Hello everyone!

When I ran the inverse-iteration example, it reports: Operation gko::as<gko::matrix::Dense<double>> does not support parameters of type gko::matrix::Dense<std::complex<double> >. I have no idea about it. May you help me?

Thank you!

**Comment by tcojean** [comment] 2020-07-30 15:03
Hi, thanks for the issue indeed we can easily reproduce this. We will fix this ASAP.

**Comment by nghiakvnvsd** [comment] 2020-07-30 15:05
And I don't know if This example can run on CudaExecutor?

**Comment by thoasm** [comment] 2020-07-30 16:18
Hello @nghiakvnvsd,
thank you very much for your feedback, this is indeed a bug.
The issue here is that the norm expects a non-complex type, which we changed not so long ago. The problem was that I forgot to check the examples for potential problems, which I will now do.
In the meantime, if you want to resolve it yourself, you can use the branch [fix_example_norms](https://github.com/ginkgo-project/ginkgo/tree/fix_example_norms) where I am currently working on resolving that for all examples, or apply the following changes:
```diff
diff --git a/examples/inverse-iteration/inverse-iteration.cpp b/examples/inverse-iteration/inverse-iteration.cpp
index 856483bfb..5be92f905 100644
--- a/examples/inverse-iteration/inverse-iteration.cpp
+++ b/examples/inverse-iteration/inverse-iteration.cpp
@@ -45,8 +45,9 @@ int main(int argc, char *argv[])
 {
     // Some shortcuts
     using precision = std::complex<double>;
-    using real_precision = double;
+    using real_precision = gko::remove_complex<precision>;
     using vec = gko::matrix::Dense<precision>;
+    using real_vec = gko::matrix::Dense<real_precision>;
     using mtx = gko::matrix::Csr<precision>;
     using solver_type = gko::solver::Bicgstab<precision>;
 
@@ -126,7 +127,7 @@ int main(int argc, char *argv[])
     }();
     auto y = clone(x);
     auto tmp = clone(x);
-    auto norm = clone(one);
+    auto norm = gko::share(gko::initialize<real_vec>({1.0}, exec));
     auto inv_norm = clone(this_exec, one);
     auto g = clone(one);
 
@@ -142,7 +143,7 @@ int main(int argc, char *argv[])
         // x = y / || y ||
         x->compute_norm2(lend(norm));
         inv_norm->get_values()[0] =
-            precision{1.0} / clone(this_exec, norm)->get_values()[0];
+            real_precision{1.0} / clone(this_exec, norm)->get_values()[0];
         x->scale(lend(clone(exec, inv_norm)));
         // g = x^* A x
         A->apply(lend(x), lend(tmp));
```

And yes, this should also run with the CudaExecutor (to be sure, I am currently running tests for that).

**Comment by thoasm** [comment] 2020-07-30 16:30
@nghiakvnvsd Can confirm that the fix also works on the CudaExecutor (should also work on HIP, but currently not when compiling for both HIP and CUDA at the same time, see PR #602 for a solution there).

**Comment by nghiakvnvsd** [comment] 2020-07-31 06:02
Thank you so much!!!

**Comment by nghiakvnvsd** [comment] 2020-08-01 06:07
I have a question about eigen values and eigen vectors. While searching ideas, I saw the topic: https://github.com/ginkgo-project/ginkgo/issues/135 . I know you guys developing it but I don't know if it finishs. I'm looking forward it because it is very useful for scientists. Thank you!

**Closed** 2020-08-12 08:27 UTC
Labels: is:bug, is:confirmed, reg:example
