### ISSUE TITLE
NaN Residuals with CUDA GMRES+ParILUT matrix part 5

### ISSUE THREAD

**Issue by iontcheva** [ginkgo-project/ginkgo#1491] opened 2023-12-05 22:20 UTC
[cis.mtx.gz.part-ae.gz](https://github.com/ginkgo-project/ginkgo/files/13573536/cis.mtx.gz.part-ae.gz)

**Comment by upsj** [comment] 2023-12-06 02:20
Duplicate of #1486

**Closed by upsj** 2023-12-06 02:20 UTC
